name: gold_coin_manager
description: مدیریت دارایی طلا و سکه با دریافت قیمت آنلاین
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  intl:
  fl_chart:
  provider:
  shared_preferences:
  hive:
  hive_flutter:
  path_provider:
  html:
  shamsi_date:
  crystal_navigation_bar: ^1.1.0
  auto_size_text:
  persian_datetimepickers: ^1.1.0
  persian_number_utility: ^1.1.6
  share_plus: ^7.2.1
  file_picker:                       # ← بدون نسخه، pub خودش بهترین نسخه را انتخاب میکند
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/icon.png
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
          weight: 400